Web/ViewModels/ImageViewModel.cs
using Core.Entities;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.ViewModels
{
    public class ImageViewModel
    {
        public string ImageUrl { get; set; }
        public int Id { get; set; }
        public string BottomText { get; set; }
        public string Album { get; set; }
        public Section Section { get; set; }

        public int SectionId { get; set; }
    }
}

Web/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amazon.S3;
using Core.Abstruct.Base;
using Core.Entities.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Web.ViewModels;

namespace Web.Controllers
{
    [Authorize]
    public class ImageController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IConfiguration _config;

        public string SecretAccessKey { get; private set; }
        public string AccessKey { get; private set; }
        public string BucketName { get; private set; }

        public ImageController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager, IConfiguration config)
        {
            this.unitOfWork = unitOfWork;
            this.userManager = userManager;
            _config = config;

             SecretAccessKey = _config.GetValue<string>("AWS:SecretAccessKey");
             AccessKey = _config.GetValue<string>("AWS:AccessKey");
             BucketName = _config.GetValue<string>("AWS:Bucket:Name");
        }

        public async Task<IActionResult> Index()
        {
            var model = new ImageListViewModel()
            {
                Images = await GetSelectedImageList(),
                Albums = await GetAllAlbums(),
                SuccessMessage = TempData["SuccessMessage"] as string
            };

            return View(model);
        }

        public async Task<IEnumerable<ImageViewModel>> GetAllAlbums()
        {
            return (await unitOfWork.ImageRepository.GetAllAlbumsAsync()).Select(a => new ImageViewModel()
            {
                Id = a.Id,
                Album = a.Album
            }).ToList();
        }
        
        public async Task<IEnumerable<ImageViewModel>> GetSelectedImageList(string Album = "Home")
        {
            return (await unitOfWork.ImageRepository.GetAllImgSelectedAlbumAsync(Album))?.Select(a => new ImageViewModel()
            {
                Id = a.Id,
                ImageUrl = a.ImageUrl,
                BottomText = a.BottomText

            }).ToList();
        }

        [HttpPost]
        public async Task<IActionResult> AddAlbumAsync(ImageListViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("Failed to Create", "Please fill all the fields correctly");
                return View(model);
            }
            var data = new Core.Entities.Image()
            {
                Album = model.Image.Album
            };

            await unitOfWork.ImageRepository.AddAsync(data, userManager.GetUserId(User));
            await unitOfWork.SaveChangesAsync();

            TempData["SuccessMessage"] = "Album created successfully!";

            return RedirectToAction("Index");
        }

        #region Amazon

        [HttpPost]
        public async Task<IActionResult> AddImageAsync(IFormFile selectedFile, ImageListViewModel model)
        {

            var imageUrl = await UploadFileToAWSAsync(selectedFile, model.Image.Album);
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("Failed to Create", "Please fill all the fields correctly");
                return View(model);
            }
            var image = unitOfWork.ImageRepository.Get(x => x.Album == model.Image.Album);
            if (image.ImageUrl == null)
            {
                image.ImageUrl = imageUrl;
                image.BottomText = model.Image.BottomText;

                unitOfWork.ImageRepository.Update(image, userManager.GetUserId(User));
                await unitOfWork.SaveChangesAsync();
            }
            else
            {
                var data = new Core.Entities.Image()
                {
                    ImageUrl = imageUrl,
                    BottomText = model.Image.BottomText,
                    Album = model.Image.Album
                };

                await unitOfWork.ImageRepository.AddAsync(data, userManager.GetUserId(User));
                await unitOfWork.SaveChangesAsync();
            }
            

            TempData["SuccessMessage"] = "Image Added to Album successfully!";
            
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int Id)
        {
            var image = await unitOfWork.ImageRepository.GetAsync(x => x.Id == Id);
            
            var imagePath = image.ImageUrl.Split('/').Last();
            imagePath = image.Album + "/" + imagePath;
            var deleteFromS3 = await DeleteFileFromAWSAsync(imagePath);

            if (Id > 0 && deleteFromS3.Item1)
            {
                unitOfWork.ImageRepository.DeletePermanantly(image);
                await unitOfWork.SaveChangesAsync();
                TempData["SuccessMessage"] = "Image Deleted successfully!";

                return RedirectToAction("Index");
            }
            else
            {
                return StatusCode(500, deleteFromS3.Item2);
            }
        }
        protected async Task<string> UploadFileToAWSAsync(IFormFile file, string album)
        {
            
            var result = "";

            try
            {
                using var s3Client = new AmazonS3Client(AccessKey, SecretAccessKey, Amazon.RegionEndpoint.APSoutheast1);
                var keyName = album + "/" + file.FileName;


                var fs = file.OpenReadStream();
                var request = new Amazon.S3.Model.PutObjectRequest
                {
                    BucketName = BucketName,
                    Key = keyName,
                    InputStream = fs,
                    ContentType = file.ContentType,
                    CannedACL = S3CannedACL.PublicRead
                };
                await s3Client.PutObjectAsync(request);

                result = string.Format("http://{0}.s3.amazonaws.com/{1}", BucketName, keyName);
            }
            catch (Exception ex)
            {
                result = ex.Message;
            }
            return result;
        }
        protected async Task<(bool, string)> DeleteFileFromAWSAsync(string filename)
        {           
            try
            {
                using var s3Client = new AmazonS3Client(AccessKey, SecretAccessKey, Amazon.RegionEndpoint.APSoutheast1);
                var bucketName = BucketName;
                var keyName = filename;

                var response = await s3Client.DeleteObjectAsync(bucketName, keyName);

                if (response.HttpStatusCode == System.Net.HttpStatusCode.NoContent)
                    return (true, string.Empty);
                return (false, $"Image server returned {response.HttpStatusCode.ToString()}");

            }
            catch (Exception ex)
            {
                return (false, ex.Message);
            }
        }
        #endregion

    }
}

Web/Views/Image/Index.cshtml
@model Web.ViewModels.ImageListViewModel
@{
    ViewData["Title"] = "AddImage";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";

    var imageList = Model.Images;
}

@section Styles{
    <style>
        .add-image form {
            width: 90%;
            display: inline-block;
        }
    </style>
}
<div class="row add-image">
    <!-- Modal -->
    <div id="AlbumPopup" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    @using (Html.BeginForm("AddAlbum", "Image", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="heading">
                            <h5>Add New Album</h5>
                            @Html.ValidationMessage("Failed to Create")
                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.Image.Album, new { @class = "form-control", @type = "text", placeholder = "Album Name" })
                            @Html.ValidationMessageFor(m => m.Image.Album)
                        </div>

                        <button type="submit" class="btn btn-info" style="float: right">Save</button>
                    }
                </div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div id="AddImagePopup" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    @using (Html.BeginForm("AddImage", "Image", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="heading">
                            <h5>Add New Image</h5>
                            @Html.ValidationMessage("Failed to Create")
                        </div>
                        <div class="form-group">
                            <input type="file" name="selectedFile" />
                        </div>
                        <div class="form-group">
                            @Html.HiddenFor(m => m.Image.Album, new { @id = "albumName" })
                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.Image.BottomText, new { @class = "form-control", placeholder = "Bottom Text" })
                            @Html.ValidationMessageFor(m => m.Image.BottomText)
                        </div>

                        <button type="submit" class="btn btn-info" style="float:right">Save</button>
                    }
                </div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div id="imagePopup" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <img src="" class="img-fluid" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    @* Show success message *@
    <div class="col-lg-12">
        @if (!string.IsNullOrEmpty(Model.SuccessMessage))
        {
            <div class="alert alert-success alert-dismissible" role="alert">
                @Model.SuccessMessage
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
    </div>
    @* End Show success message *@

    <div class="col-lg-3 p-2">
        <fieldset class="border p-4">
            <legend class="w-auto pl-4 pr-4 text-left"> <button class="btn btn-info" id="creatAlbumBtn">+Create New Album</button></legend>
            @foreach (var a in Model.Albums)
            {
                <div class="row justify-content-center py-1">
                    <div class="col-lg-10 album-wrap">
                        <button class="btn btn-info btn-block" id="@a.Album">@a.Album</button>
                    </div>
                </div>
            }
        </fieldset>
    </div>

    <div class="col-lg-9 p-2 images-div">
        <fieldset class="border p-4">
            <legend class="w-auto pl-4 pr-4 text-right"><button class="btn btn-info" id="addImageBtn" disabled>+ Add New Image</button></legend>
            <div class="row" id="imageView">
            </div>
        </fieldset>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#creatAlbumBtn').on('click', () => {
                $('#AlbumPopup').appendTo("body").modal('show');
            });
            $('#addImageBtn').on('click', () => {
                $('#AddImagePopup').appendTo("body").modal('show');
            });

            //image on click
             $(document).on('click', '.img-wrap .img-thumbnail', function(){
                src = $(this).attr('src');
                $('#imagePopup img').attr('src', src);
                $('#imagePopup').appendTo("body").modal('show');

            });


            //image delete btn click
            $(document).on('click', '.delete ', function () {
                var id = $(this).attr('id');
                  if (confirm("Are you sure?")) {
                    $.ajax({
                    url: '@Url.Action("Delete", "Image")',
                    type: "GET",
                    data: { Id: id },
                    beforeSend: function() {
                    },
                    success: function(response){
                        //console.log(response);
                        $(this).closest(".img-wrap").remove();
                    },
                    error: function(xhr) {
                        alert("Something went wrong, please contact Admin");
                        console.error(xhr);
                    },
                    complete: function() {
                    }
                });
                }
                return false;
             });

            //modal on close
            $('#imagePopup').on('hidden.bs.modal', function () {
                $('#imagePopup img').attr('src', '');
            })


            //album button on click
            $('.album-wrap button').on("click", function (e) {
                e.preventDefault();
                $(".album-wrap button").removeClass('active');
                $(this).toggleClass('active');

                $('#addImageBtn').attr('disabled', false);
                album = $(this).attr('id');

                //put albam name to add image form
                $('#albumName').val(album);

                //get all images for selected album
                $.ajax({
                    url: '@Url.Action("GetSelectedImageList", "Image")',
                    type: "GET",
                    data: { Album: album },
                    beforeSend: () => {
                    },
                    success: response => {
                       // console.log(response);

                            var newHtml = "";
                        $.each(response, function (index, value) {
                            if (value.imageUrl) {
                                newHtml += '<div class="col-lg-3 img-wrap">';
                                newHtml += '<a class="delete" id="' + value.id + '"><img src="/images/deleteIcon.png" class="img-fluid deleteBtn" alt=""></a>';
                                newHtml += '<img src="' + value.imageUrl + '" class="img-fluid img-thumbnail" alt="">';
                                newHtml += '</div>';
                            }
                            else {
                                newHtml += '<div class="col-lg-12 img-wrap">';
                                newHtml += '<h1 class="text-center">No Image Uploaded<h1>';
                                newHtml += '</div>';
                            }
                            });
                            $("#imageView").html(newHtml);
                    },
                    error: xhr => {
                        alert("Something went wrong, please contact Admin");
                        console.error(xhr);
                    },
                    complete: () => {
                    }
                });


            });
        });
    </script>
}

Web/Views/Image/_ImagePopupModal.cshtml
<!-- Modal -->
<div id="imagePopup" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="row px-5 ">
                <div class="col-lg-3 p-2">
                    <fieldset class="border p-4">
                        <legend class="w-auto pl-4 pr-4 text-left">Select Album</legend>
                        @if (@Model.Albums != null)
                        {
                            @foreach (var a in Model.Albums)
                            {
                                <div class="row justify-content-center py-1">
                                    <div class="col-lg-10 album-wrap">
                                        <button class="btn btn-info btn-block" id="@a.Album">@a.Album</button>
                                    </div>
                                </div>

                            }
                        }

                    </fieldset>
                </div>

                <div class="col-lg-9 p-2 images-div">
                    <fieldset class="border p-4">
                        <legend class="w-auto pl-4 pr-4 text-right">Select Image</legend>
                        <div class="row" id="imageView">
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>